language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: VMsFMdLS+fPj/EmgEgHG96KvBzmkllnCImDJcQH8zz36juRpcvXO87Cq14eXKc7Y3D/y5HWO+Vyo+nOODsvRsnwON7dVEgbjT+udkrfa61JH1GtU5IRJKDxk5Hg2FwyuqBXGHEXA4JJ68oqP5eUAOl+abgVX6MiOTuzNYqqc2wrSDpwGDSi79mgBIQZY9/rFCUxuAn0shTecVR/5sM7rRM3eW5QypSWWiTHWP1QalVWrUO6BMkzXwLGm/+X/KErMhkSwah0M5MAZlWqFsnlslvJhdbVZysfco0E1S1HHiea2vUroZGe8rewaQfRhpXF6vsehp7PNcbhED+U58lurYP9yK3uDL101ed8JAgz3Xw0XZ1z52QdJQ7foL6UDFEFWmF5XhSMgJJkU0sG/L8Bihn9dFQUewY/qko9ik7X7qmYOBw79BXjXH3msN+HdR/nS+2U8eg34h0iEtyXYN94Kos23cwX7x2GJPrr4aRcdpTz/uT3UzfUpFdSkIZLvFLLJz0w4BbJKNXwyBsh9785V1BxeyYW+hoq2yRBhjwJNOleIOxqf2QKu1zYcmE/gjQ/RSJH5zG2Yhn7Xy+hkq2WpbprFUXtabOeA9sul5NoK5zrJdrdRpDQ6x8Y7Lj0XAADhp3bG2Mw8ZPaiiLi3XvI0RTC+b3mIuHQRr+lAvgzVm7Y=
  app: serene-hollows-7849
  on:
    repo: hyoshiok/rakuten_enpit_example
